export const mockUsers = [
    {
        id: '1',
        name: 'Jamison Nord',
        avatar: '',
        role: 'Operations Manager',
        division: 'Operations',
        country: 'Germany',
        countryCode: 'DE',
        poolingCenter: 'Frankfurt Pooling Center (SPCFRA)',
        email: 'sarah.johnson@superb.com',
        phone: '+1 234-567-8901',
        status: 'active' as const,
        lastLogin: '2hr ago',
    },
    {
        id: '2',
        name: 'River James',
        avatar: '',
        role: 'Operations Manager',
        division: 'Operations',
        country: 'Germany',
        countryCode: 'DE',
        poolingCenter: 'Frankfurt Pooling Center (SPCFRA)',
        email: 'sarah.johnson@superb.com',
        phone: '+1 234-567-8901',
        status: 'active' as const,
        lastLogin: '2hr ago',
    },
    {
        id: '3',
        name: 'Hadley Yu',
        avatar: '',
        role: 'Operations Manager',
        division: 'Operations',
        country: 'Germany',
        countryCode: 'DE',
        poolingCenter: 'Frankfurt Pooling Center (SPCFRA)',
        email: 'sarah.johnson@superb.com',
        phone: '+1 234-567-8901',
        status: 'active' as const,
        lastLogin: '2hr ago',
    },
    {
        id: '4',
        name: 'Dakota Alvarez',
        avatar: '',
        role: 'Operations Manager',
        division: 'Operations',
        country: 'Germany',
        countryCode: 'DE',
        poolingCenter: 'Frankfurt Pooling Center (SPCFRA)',
        email: 'sarah.johnson@superb.com',
        phone: '+1 234-567-8901',
        status: 'active' as const,
        lastLogin: '2hr ago',
    },
];

export const mockNewRequests = [
    {
        id: '1',
        name: 'Jamison Nord',
        email: 'Jamison.Nord@superb.com',
        avatar: '',
        role: 'Operations Manager',
        division: 'Operations',
        country: 'Germany',
        countryCode: 'DE',
        poolingCenter: 'Frankfurt Pooling Center (SPCFRA)',
        requestedDate: '2024-12-02',
    },
    {
        id: '2',
        name: 'Maisy Williams',
        email: 'Maisy.Williams@superb.com',
        avatar: '',
        role: 'Operations Manager',
        division: 'Operations',
        country: 'Germany',
        countryCode: 'DE',
        poolingCenter: 'Frankfurt Pooling Center (SPCFRA)',
        requestedDate: '2024-12-02',
    },
    {
        id: '3',
        name: 'Kellan Dietz',
        email: 'Kellan.Dietz@superb.com',
        avatar: '',
        role: 'Operations Manager',
        division: 'Operations',
        country: 'Germany',
        countryCode: 'DE',
        poolingCenter: 'Frankfurt Pooling Center (SPCFRA)',
        requestedDate: '2024-12-02',
    },
    {
        id: '4',
        name: 'Ricardo Abner',
        email: 'Ricardo.Abner@superb.com',
        avatar: '',
        role: 'Operations Manager',
        division: 'Operations',
        country: 'Germany',
        countryCode: 'DE',
        poolingCenter: 'Frankfurt Pooling Center (SPCFRA)',
        requestedDate: '2024-12-02',
    },
];
